# Generated by Django 2.1.3 on 2018-11-27 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steambird', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.URLField(blank=True, null=True, verbose_name='Link to cover image of book'),
        ),
        migrations.AlterField(
            model_name='course',
            name='materials',
            field=models.ManyToManyField(blank=True, null=True, to='steambird.MaterialSelectionProcess', verbose_name='The list of materials relevant for this course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='steambird.Module', verbose_name='Links course to possible module (maths) if needed'),
        ),
    ]
