# Generated by Django 2.1.7 on 2019-03-28 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steambird', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursestudy',
            options={'verbose_name': 'Course-Study relation', 'verbose_name_plural': 'Course-Study relations'},
        ),
        migrations.AlterModelOptions(
            name='msp',
            options={'verbose_name': 'Material Selection Process', 'verbose_name_plural': 'Material Selection Processes'},
        ),
        migrations.AlterModelOptions(
            name='mspline',
            options={'ordering': ['time'], 'verbose_name': 'Material Selection Process line', 'verbose_name_plural': 'Material Selection Process lines'},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name': 'Study', 'verbose_name_plural': 'Studies'},
        ),
    ]
