# Generated by Django 2.1.3 on 2018-11-26 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steambird', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterialedition',
            name='material_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='steambird.StudyMaterial'),
        ),
    ]
