# Generated by Django 2.1.3 on 2018-11-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambird', '0002_auto_20181126_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name_plural': 'studies'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_login',
            field=models.DateTimeField(null=True, verbose_name='Last Login'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='surname_prefix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
