# Generated by Django 2.1.3 on 2018-11-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambird', '0002_auto_20181127_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='name',
            field=models.CharField(default='UNKNOWN', max_length=255, verbose_name='Category name of this article'),
            preserve_default=False,
        ),
    ]
