# Generated by Django 2.1.4 on 2019-03-14 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steambird', '0003_studymaterial_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='materialselectionprocess',
            options={'verbose_name': 'Material Selection Process', 'verbose_name_plural': 'Material Selection Processes'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='othermaterial',
            options={'verbose_name': 'Other Material', 'verbose_name_plural': 'Other Materials'},
        ),
        migrations.AlterModelOptions(
            name='scientificarticle',
            options={'verbose_name': 'Scientific Article', 'verbose_name_plural': 'Scientific Articles'},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name': 'Study', 'verbose_name_plural': 'Studies'},
        ),
        migrations.AlterModelOptions(
            name='studycourse',
            options={'verbose_name': 'StudyCourse', 'verbose_name_plural': 'StudyCourse'},
        ),
        migrations.AlterModelOptions(
            name='studymaterial',
            options={'verbose_name': 'Study Material', 'verbose_name_plural': 'Study Materials'},
        ),
        migrations.AlterModelOptions(
            name='studymaterialedition',
            options={'verbose_name': 'StudyMaterial Edition', 'verbose_name_plural': 'StudyMaterials Editions'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Edition of the book (if applicable)'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Category name of this article'),
        ),
        migrations.AlterField(
            model_name='studymaterialedition',
            name='material_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='steambird.StudyMaterial', verbose_name='Material collection'),
        ),
    ]
