# Generated by Django 2.1.3 on 2018-11-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambird', '0003_auto_20181126_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Login'),
        ),
    ]
