# Generated by Django 2.1.7 on 2019-03-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambird', '0003_auto_20190328_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default=0, max_length=64, verbose_name='Course Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='updated_associations',
            field=models.BooleanField(default=False, verbose_name='Updated by association?'),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_teacher',
            field=models.BooleanField(default=False, verbose_name='Updated by teacher?'),
        ),
    ]
