# Generated by Django 2.1.7 on 2019-03-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambird', '0004_auto_20190328_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Name of study'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name of this course'),
        ),
        migrations.AlterField(
            model_name='study',
            name='slug',
            field=models.SlugField(verbose_name='Abbreviation of the study'),
        ),
    ]
