# Generated by Django 2.1.8 on 2019-05-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambird', '0005_auto_20190328_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
