# Generated by Django 2.1.8 on 2019-05-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambird', '0006_auto_20190509_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudy',
            name='study_year',
            field=models.IntegerField(help_text='In which year the course is given for this study', verbose_name='N-th year'),
        ),
    ]
