# Generated by Django 2.1.8 on 2019-05-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambird', '0007_auto_20190520_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='period',
            field=models.CharField(choices=[('Q1', 'Quartile 1'), ('Q2', 'Quartile 2'), ('Q3', 'Quartile 3'), ('Q4', 'Quartile 4'), ('Q5', 'Quartile 5 (sad summer students)'), ('Q1_HALF', 'Quartile 1, half year course'), ('Q2_HALF', 'Quartile 2, half year course'), ('Q3_HALF', 'Quartile 3, half year course'), ('FULL_YEAR', 'Full year course')], max_length=32, verbose_name='The period in the year for this course'),
        ),
    ]
