# Generated by Django 2.1.8 on 2019-06-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambird', '0009_auto_20190606_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudy',
            name='study_year',
            field=models.IntegerField(blank=True, choices=[('Y1', 1), ('Y2', 2), ('Y3', 3), ('Y4', 4)], null=True, verbose_name='The year of (nominal) study this course is given'),
        ),
    ]
