# Generated by Django 2.1.8 on 2019-06-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steambird', '0011_auto_20190611_1527'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursestudy',
            unique_together={('study', 'course', 'study_year')},
        ),
    ]
