# Generated by Django 2.1.8 on 2019-06-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambird', '0013_scientificarticle_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudy',
            name='study_year',
            field=models.IntegerField(blank=True, choices=[(1, 'Jaar 1'), (2, 'Jaar 2'), (3, 'Jaar 3'), (4, 'Jaar 4')], null=True, verbose_name='The year of (nominal) study this course is given'),
        ),
        migrations.AlterField(
            model_name='scientificarticle',
            name='DOI',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Digital Object Identifier'),
        ),
    ]
