# Generated by Django 2.1.9 on 2019-06-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('steambird', '0015_config'), ('steambird', '0016_auto_20190626_2336')]

    dependencies = [
        ('steambird', '0014_auto_20190620_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, default=2019, null=True, verbose_name='Current year you are working in')),
                ('period', models.CharField(choices=[('Q1', 'Quartile 1'), ('Q2', 'Quartile 2'), ('Q3', 'Quartile 3'), ('Q4', 'Quartile 4'), ('Q5', 'Quartile 5 (sad summer students)'), ('Q1_HALF', 'Quartile 1, half year course'), ('Q2_HALF', 'Quartile 2, half year course'), ('Q3_HALF', 'Quartile 3, half year course'), ('FULL_YEAR', 'Full year course')], default='Q1', max_length=32, verbose_name='The period in the year you are working in')),
            ],
        ),
    ]
