# Generated by Django 2.1.8 on 2019-06-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steambird', '0015_auto_20190620_2216'),
        ('steambird', '0015_config_squashed_0016_auto_20190626_2336'),
    ]

    operations = [
    ]
