# Generated by Django 2.1.9 on 2019-06-29 17:07

from django.db import migrations, models


def add_empty_config(apps, schema_editor):
    Config = apps.get_model('steambird', 'config')
    if not Config.objects.first():
        Config().save()


class Migration(migrations.Migration):

    dependencies = [
        ('steambird', '0017_auto_20190629_1907'),
    ]

    operations = [
        migrations.RunPython(add_empty_config)
    ]
