# Generated by Django 2.1.10 on 2019-09-01 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('steambird', '0018_add_default_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studymaterial',
            options={'verbose_name': 'Study Material Collection', 'verbose_name_plural': 'Study Material Collections'},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_login',
        ),
        migrations.AddField(
            model_name='mspline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator of this MSP line'),
        ),
        migrations.AddField(
            model_name='mspline',
            name='created_by_side',
            field=models.CharField(choices=[('BOECIE', 'Boecie'), ('TEACHER', 'Teacher')], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='materials',
            field=models.ManyToManyField(blank=True, to='steambird.MSP', verbose_name='Materials that are required by this course'),
        ),
        migrations.AlterField(
            model_name='coursestudy',
            name='study_year',
            field=models.IntegerField(blank=True, choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')], null=True, verbose_name='The year of (nominal) study this course is given'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='The user associated to this teacher'),
        ),
    ]
