# Generated by Django 2.1.10 on 2019-09-05 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('steambird', '0019_auto_20190901_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Token that will be placed in the auth endpoint')),
                ('last_host', models.GenericIPAddressField(blank=True, default=None, null=True, verbose_name='Last location that this token was used.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User that will log in with given token')),
            ],
        ),
    ]
