# Generated by Django 2.1.10 on 2019-09-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambird', '0020_authtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='othermaterial',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name="Description of an 'other material', can be expected to contain any sort of reference like links of sorts to make it clear what the exact product would be"),
        ),
    ]
