# Generated by Django 2.1.12 on 2019-09-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambird', '0021_othermaterial_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='titles',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Academic titles'),
        ),
    ]
