stages:
  - prepare
  - test
  - build
  - deploy

variables:
  PIPENV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pipenv"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

include:
  # Validate runs dependency validation, license validation and syntax checks
  - local: /.gitlab/prepare.yml
  # Test runs unit tests, browser tests and integration tests
  - local: /.gitlab/test.yml
  # Deploy deploys to various hosts
  - local: /.gitlab/deploy.yml
