stages:
  - test
  - build
  - deploy

deploy-docker:
  stage: deploy
  only:
    - /^release/.*$/
  except:
    - branches
  when: manual
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$DOCKER_REGISTRY\":{\"username\":\"$DOCKER_REGISTRY_USERNAME\",\"password\":\"$DOCKER_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - export VERSION=$(echo $CI_COMMIT_TAG | cut -d'/' -f2)
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $DOCKER_REGISTRY/$CI_PROJECT_PATH_SLUG:$VERSION --destination $DOCKER_REGISTRY/$CI_PROJECT_PATH_SLUG:latest
