version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: stoomvogel
      POSTGRES_PASSWORD: stoomvogel
      POSTGRES_DB: stoomvogel
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
