name: Run pylint
on: [push]
jobs:
  do-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d
      - name: Lint
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run pylint --rcfile=.pylintrc steambird -dfixme

